name: PR to Dev Merged

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  # First CI run
  ci-before:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/ci.yml

  # Version bump
  version-bump:
    needs: ci-before
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version (patch)
        run: |
          npm version patch -m "chore: bump version to %s [skip ci]"

      - name: Push changes
        run: git push --follow-tags

  # Second CI run after version bump
  ci-after:
    needs: version-bump
    uses: ./.github/workflows/ci.yml